version: '3.8'

services:
  auth:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - /app/target
      - ~/.m2:/root/.m2
    env_file: .env
    networks:
      - webnet
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: rotax_postgres
    environment:
      POSTGRES_DB: rotax_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - rotax-db-data:/var/lib/postgresql/data
    networks:
      - webnet

volumes:
  rotax-db-data:

networks:
  webnet:
    driver: bridge